gas_adjustment = 1.5
gas_prices = "500000akii"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "SOL"
threshold = "2"

[[deviation_thresholds]]
base = "XRP"
threshold = "2"

[[deviation_thresholds]]
base = "BNB"
threshold = "2"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

[[deviation_thresholds]]
base = "USDC"
threshold = "2"

[[deviation_thresholds]]
base = "XAUT"
threshold = "2"

[[currency_pairs]]
base = "BTC"
chain_denom = "ubtc"
providers = [
  "huobi",
  "coinbase",
  "kraken",
  "okx"
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
chain_denom = "ueth"
providers = [
  "huobi",
  "coinbase",
  "kraken",
  "okx"
]
quote = "USDT"

[[currency_pairs]]
base = "SOL"
chain_denom = "usol"
providers = [
  "huobi",
  "kraken",
  "coinbase",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "XRP"
chain_denom = "uxrp"
providers = [
  "huobi",
  "kraken",
  "coinbase",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "BNB"
chain_denom = "ubnb"
providers = [
  "huobi",
  "kraken",
  "okx",
]
quote = "USDT"

[[currency_pairs]]
base = "USDT"
chain_denom = "uusdt"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
chain_denom = "uusdc"
providers = [
  "huobi",
  "kraken",
  "okx",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "XAUT"
chain_denom = "uxaut"
providers = [
  "huobi",
  "okx",
  "gate",
]
quote = "USDT"

[account]
address = "kii10jmp6sgh4cc6zt3e8gw05wavvejgr5pwfe2u6n"
chain_id = "localchain_1010-1"
validator = "kiivaloper10jmp6sgh4cc6zt3e8gw05wavvejgr5pwu030m8"
prefix = "kii"


[keyring]
backend = "test"
dir = "~/.kiichain"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "500ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable_hostname = true
enable_hostname_label = true
enable_service_label = true
enabled = true
global_labels = [["chain_id", "localchain_1010-1"]]
service_name = "price-feeder"
prometheus_retention = 60

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"
